### ISSUE TITLE
Some filetypes don't carry metadata

### ISSUE THREAD

**Issue by nickdesaulniers** [nickdesaulniers/audiostream#10]
or atleast metadata readable by musicmetadata
https://github.com/leetreveil/node-musicmetadata/issues/13

So this causes the index listing to hang, since it's waiting for the last files metadata event.

**Comment by nickdesaulniers** [comment]
looks like this is the case with .wav files.  There is an additional flag for ffmpeg, but it doesn't seem necessary and doesn't solve the .wav metadata issue:
`ffmpeg -i input.file1 -map_metadata 0:s:0 output.file2`

**Comment by englercj** [comment]
Should we use the user-defined meta data, or a service to lookup metadata so we can build information for untagged songs; just like most desktop music managers do.

**Comment by nickdesaulniers** [comment]
So for the metadata result, the sane default if the title doesn't exist should just be the filename:
https://github.com/nickdesaulniers/audiostream/issues/13
I really like the idea of user-defined metadata.  That's going to require a db backend.  A separate import [script](https://npmjs.org/doc/scripts.html) would be nice to import or populate the db.  Like an `$ npm import` or something.  And a shim/abstraction between backends would be nice.

**Comment by englercj** [comment]
You thinking too small BRO, once installed the user should be able to manage ERREHTIN from the UI

**Comment by nickdesaulniers** [comment]
I don't know how I feel about letting them choose folders through the web.  Someone cracks your password, then picks `~/`.   We have regex support, for the files mapped, but I'm still worried.  But running the indexing from the web would be neat.  Less command line, more web app?
ERRBUDY in the club gettin' tipz.

**Comment by englercj** [comment]
If someone gets your password and adds `~/`, so what? They mesed up your library and you can repair it. I don't see an issue with managing everything via the UI.

Deploy should be `git clone xxx && cd xxx && npm install`

Any configuration, and management should be done via the webapp. So much easier that way.

**Comment by nickdesaulniers** [comment]
we could hash the password and store the hash in the config file!!! oOo

**Comment by englercj** [comment]
or the database lol

**Comment by nickdesaulniers** [comment]
yeah, whatever.  Why not have the deploy then be just `$ npm install -g audiostream` and it be in a state where you configure your username/password on first run?

**Comment by englercj** [comment]
That's exactly what should happen.

**Comment by nickdesaulniers** [comment]
Sensible defaults work fine for now.  We may later choose to re-investigate letting the user modify metadata.
