### ISSUE TITLE
Serve static html index view, send data over ajax

### ISSUE THREAD

**Issue by nickdesaulniers** [nickdesaulniers/audiostream#11]
It's probably more responsive to serve a static html index page, then request the file data as json.

**Comment by nickdesaulniers** [comment]
http://datatables.net/release-datatables/examples/ajax/objects.html

**Comment by nickdesaulniers** [comment]
Playing around with dataTable, it doesn't scale the widths of the td's right when getting data asynchronously.  I'm really not happy with it.  Might swap it out for something else:
http://flexigrid.info/
http://www.jtable.org/

**Comment by sr-ix** [comment]
For reference, I serve my own website(s) with <a href="https://github.com/cloudhead/node-static">node-static</a> and I'm pretty pleased with it.

**Comment by nickdesaulniers** [comment]
node-static is neat, but kinda isn't needed in addition to express, and certainly not behind nginx/apache.  The goal is to have something like nginx serve all static content, and express only receives requests for dynamic content.

**Comment by nickdesaulniers** [comment]
https://github.com/nickdesaulniers/audiostream/commit/f8f3e351e62586f3e38b8311704349702b2f0458
