### ISSUE TITLE
Attempts to play files not supported by a browser hang the player

### ISSUE THREAD

**Issue by sr-ix** [nickdesaulniers/audiostream#14]
Seen on Firefox - The player attempts to play mp3 files as ogg, which returns an error to the node console but does not notify the browser of this error.

**Comment by nickdesaulniers** [comment]
Can you paste in the node error?

The application should detect which files are supported and properly transcode the file.  The audio tag is used for a more native experience (instead making a custom player that everyone sees, maybe down the road).  The player should not hang.  The progress meter should never be removed, and no, there are no error callbacks to remove the progress bar currently written.  I'll look into error callbacks for trying to load media sources.

**Comment by nickdesaulniers** [comment]
You can just add an event listener for the 'error' event to the audio element.  This seems like a nice spot for it:
https://github.com/nickdesaulniers/audiostream/blob/master/public/javascripts/myscript.js#L70
(above it).  Would you like to contribute the patch?  It should remove the innnerHTML of the div#controls element, and maybe put an error message in there.

**Comment by sr-ix** [comment]
Good news, everyone! The update to musicmetadata solved this one for us.

**Comment by nickdesaulniers** [comment]
It's not user friendly if the media request fails.
