### ISSUE TITLE
Specifying Node versions in Package.json

### ISSUE THREAD

**Issue by RenatoGoi** [nickdesaulniers/audiostream#15]
Is it possible to specify the node and npm versions in the package.json? 
Perhaps as

"engines": {
    "node": "0.8.12",
    "npm": "1.1.49"
  }

For people who run different versions of node and because express doesn't work with node versions that are under 0.5.0.

**Comment by nickdesaulniers** [comment]
good idea, I've only tested with v0.8.14
Should I list v0.8.14, or try to test with older versions of node (@englercj)?  I have [nvm](https://github.com/creationix/nvm) so it wouldn't be too hard.

**Comment by englercj** [comment]
I would try it with v0.6, but we can target v0.8 (and we probably should)

**Comment by nickdesaulniers** [comment]
@RenatoGoi , expressjs v3.0.1 engine dependencies are listed as *:
https://github.com/visionmedia/express/blob/master/package.json#L54

**Comment by englercj** [comment]
@nickdesaulniers Ya, thats bullshit

**Comment by nickdesaulniers** [comment]
@englercj They can't put anything on the internet that isn't true. ;)

**Comment by nickdesaulniers** [comment]
I should probably also whitelist darwin and linux, since I've tested it on both.

**Comment by nickdesaulniers** [comment]
the dependency is now up to v0.8.14, I will test a few others and update

**Comment by nickdesaulniers** [comment]
hmmm npm definitely ignores the engine directive, I just built node v0.6.0 and did npm install and it did, without any complaints.

**Comment by englercj** [comment]
RTFM:

https://npmjs.org/doc/json.html#engines

> Note that, unless the user has set the `engine-strict` config flag, this field is **advisory only**.

I think that even with `engineStrict` this field is just for the user, npm doesn't really use it.

**Comment by nickdesaulniers** [comment]
ah, had to update my npm man pages:
`$ npm update -g`
I'm adding an npm field, but not changing it to [engineStrict](https://npmjs.org/doc/json.html#engineStrict).  If someone wants to verify it works in a greater range or on windows, and can prove it, I'll modify the package.json as needed.
