### ISSUE TITLE
Duration

### ISSUE THREAD

**Issue by nickdesaulniers** [nickdesaulniers/audiostream#18]
Add the duration to the info sent to the client.  This can not be read from the metadata tags, so I'm not sure how to implement this.  Can be done client side, but that requires loading each audio file.

**Comment by englercj** [comment]
It can be determined using the bitrate and filesize; something like [jPlayer](http://www.jplayer.org/) will do this for you automagically I think.

**Comment by nickdesaulniers** [comment]
That requires loading/requesting the file.  I meant to show the duration in the table listing.

**Comment by englercj** [comment]
you are stating the file server side, calculate it there.

**Comment by leetreveil** [comment]
You can use ffmpeg to read the duration:

http://stackoverflow.com/questions/7395343/get-length-of-a-video-using-regex-and-ffmpeg

**Comment by englercj** [comment]
Even better!

**Comment by nickdesaulniers** [comment]
`ffmpeg -i while_my_guitar_gently_weeps.mp3 2>&1 | grep Duration | cut -f2- -d: | cut -f1 -d, | tr -d ' '`
just worked for me.  Thanks @leetreveil

**Comment by nickdesaulniers** [comment]
[fixed in redesign branch](https://github.com/nickdesaulniers/audiostream/commit/cfe9f5ef6a2bfaaff89a871790593751211e0dd0)
