### ISSUE TITLE
npm script to clear out cache/transcoded media in library/

### ISSUE THREAD

**Issue by nickdesaulniers** [nickdesaulniers/audiostream#19]
`$ npm empty`
Deletes all files in `/library` except the .gitignore and the folder itself.
https://npmjs.org/doc/scripts.html

**Comment by englercj** [comment]
`npm run-script empty`? Or does `npm <custom-stage>` actually work now?

**Comment by nickdesaulniers** [comment]
idk, have not yet investigated.
