### ISSUE TITLE
Use a Stream instead of a Buffer for responses for media?

### ISSUE THREAD

**Issue by nickdesaulniers** [nickdesaulniers/audiostream#21]
Not sure if this is possible:
http://jackietutorial.blogspot.com/2012/07/stream-file-to-android-using-nodejs-and.html
https://github.com/schaermu/node-fluent-ffmpeg/blob/master/examples/express-stream.js#L20
https://github.com/schaermu/node-fluent-ffmpeg/blob/master/lib/processor.js#L108

**Comment by nickdesaulniers** [comment]
In testing, this didn't make a difference, just adds to the code since you need to specify the response type.

**Comment by englercj** [comment]
It would make a difference if one site is serving many clients, but are you sure that sendFile uses a Buffer and not a Stream?

**Comment by nickdesaulniers** [comment]
https://github.com/visionmedia/express/blob/master/lib/response.js#L26
http://nodejs.org/api/http.html#http_class_http_serverresponse
Looks like a stream.

**Comment by englercj** [comment]
Yeah I thought it might be, as long as you dont read it into a buffer, then send it to the client it will be fine :P
