### ISSUE TITLE
Cache invalidation strategy is weak

### ISSUE THREAD

**Issue by nickdesaulniers** [nickdesaulniers/audiostream#25]
Hashing the ajax response doesn't guarantee the resulting JSON from the server is in the same order.  Sorting the results would also suck.  Maybe keep track of the watched folders' mtime.

**Comment by englercj** [comment]
unique or sequence IDs?

**Comment by nickdesaulniers** [comment]
@englercj please elaborate.

**Comment by englercj** [comment]
Have a sequence or unique ID that represents the state of the folder; whenever there is a change, increment/change the ID. A timestamp works nicely, and in translating to a DB backend, you can just have a document that is updated with the latest timestamp as a post-insert/update hook.

A lot of times we use the JS timestamp for this so we can not only see that it has changed, but when and how long ago, etc. CouchDB has the idea of "revisions" of a document, so each "revision" has an ID; that would also be a good option.

**Comment by nickdesaulniers** [comment]
```
$ node
> var fs = require('fs');
> fs.statSync('.').mtime;
> .exit
$ stat -x .
```

**Comment by englercj** [comment]
that doesn't work to well on a database :P

**Comment by nickdesaulniers** [comment]
Sure, but as an example:
- User sets app to watch /music
- User modifies files within /music without going through the app
- cache does not get invalidated

So in the db it may make sense to store the mtimes of folders when they are added through the app, and then when the request for the file list comes in, we check each folders' mtime vs what's in the db, return HTTP 304 if no change, else rebuild db mtimes and send new listing.

**Comment by englercj** [comment]
If you store the files outside the database, then sure; we are thinking in two different architectures.

**Comment by nickdesaulniers** [comment]
http://stackoverflow.com/a/3751/1027966

**Comment by nickdesaulniers** [comment]
http://programmers.stackexchange.com/a/150681

**Comment by englercj** [comment]
One of those is over 2 years old, and the other is talking about SQL databases. Besides the biggest benefit isn't performance; manageability, ease of access, and control are all better with a database than a raw fs. But whatever, I'm just beating a dead horse at this point.

**Comment by nickdesaulniers** [comment]
@englercj , no, you know a lot more about more things than me.  I'm sorry I did not understand you were referring to NoSQL solutions, as when you refer to 'documents' instead of tables.  I really know nothing about NoSQL backends.

**Comment by nickdesaulniers** [comment]
The cache should be updated when a new folder is added to be watched.  That functionality will be added later, so we can open a new issue then.
