### ISSUE TITLE
Filenames with ".\ " are not listed?

### ISSUE THREAD

**Issue by nickdesaulniers** [nickdesaulniers/audiostream#28]
Can't really verify right now, but seems like filenames that have a ".\ " in them aren't being listed.  Ex. "01.\ Papercut.flac"

**Comment by nickdesaulniers** [comment]
Nope, I forgot you have to restart the server after modifying config/config.json.  I should change that.

**Comment by englercj** [comment]
I like to open a socket with [dshaw/replify](https://github.com/dshaw/replify) and use it to have management commands (like reloading config). I usually use something like [socat](http://linux.die.net/man/1/socat) to have a command line interface with it live running.

Authenticated REST calls work too :stuck_out_tongue:
